name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # How to fix ANSI color codes w/ GH actions:
        # See https://github.com/orgs/community/discussions/26944
        shell: 'script -q -e -c "export TERM=xterm-256color; bash --noprofile --norc -eo pipefail {0}"'

    steps:
      - name: Setup curl
        uses: kordlib/setup-curl@v1.0.2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Run tests
        run: bundle exec rspec spec/ -f p
